# Requirements: mkdir -p ./logs/kafka{1,2,3}


x-environment-common: &environment-common
  KAFKA_CONFIG_SOURCE: env
  CLUSTER_ID: w3rNt4dlTIW_RoSUh7cmAQ
  #log4j.logger.kafka: DEBUG
  #log4j.logger.org.apache.kafka: DEBUG
  server.auto.create.topics.enable: "false"
  server.inter.broker.listener.name: INTERNAL
  server.controller.listener.names: CONTROLLER
  server.listener.security.protocol.map: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
  server.listeners: INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093

services:
  kafka1:
    image: moukoublen/kafka:latest
    ports:
      - "19101:9094"
    environment:
      <<: *environment-common
      server.node.id: 1
      server.broker.id: 1
      server.advertised.listeners: INTERNAL://kafka1:9092,EXTERNAL://localhost:19101
      server.controller.quorum.voters: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      server.process.roles: broker,controller
    restart: on-failure
    volumes:
    - type: bind
      source: ./logs/kraft-kafka1
      target: /kafka-logs

  kafka2:
    image: moukoublen/kafka:latest
    ports:
      - "19102:9094"
    environment:
      <<: *environment-common
      server.node.id: 2
      server.broker.id: 2
      server.advertised.listeners: INTERNAL://kafka2:9092,EXTERNAL://localhost:19102
      server.controller.quorum.voters: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      server.process.roles: broker,controller
    restart: on-failure
    volumes:
    - type: bind
      source: ./logs/kraft-kafka2
      target: /kafka-logs

  kafka3:
    image: moukoublen/kafka:latest
    ports:
      - "19103:9094"
    environment:
      <<: *environment-common
      server.node.id: 3
      server.broker.id: 3
      server.advertised.listeners: INTERNAL://kafka3:9092,EXTERNAL://localhost:19103
      server.controller.quorum.voters: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      server.process.roles: broker,controller
    restart: on-failure
    volumes:
    - type: bind
      source: ./logs/kraft-kafka3
      target: /kafka-logs

## You can choose and uncomment one (or more) of those admin panels.

  # kafdrop:
  #   # https://github.com/obsidiandynamics/kafdrop
  #   image: obsidiandynamics/kafdrop:latest
  #   ports:
  #     - 9000:9000
  #   environment:
  #     KAFKA_BROKERCONNECT: kafka1:9092,kafka2:9092,kafka3:9092
  #     JVM_OPTS: -Xms32M -Xmx64M
  #     SERVER_SERVLET_CONTEXTPATH: /

  # kafka-ui:
  #   # https://github.com/provectus/kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092

  # akhq:
  #   # https://github.com/tchiotludo/akhq
  #   image: tchiotludo/akhq:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     AKHQ_CONFIGURATION: |
  #       akhq:
  #         connections:
  #           docker-kafka-server:
  #             properties:
  #               bootstrap.servers: "kafka1:9092,kafka2:9092,kafka3:9092"


networks:
  kafkanet: {}
  default:
    name: kafkanet
