version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.5.8
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    image: moukoublen/kafka
    ports:
      - "9094:9094"
    environment:
      server.broker.id: 1
      server.zookeeper.connect: zookeeper:2181
      server.listeners: INSIDE://kafka:9092,OUTSIDE://kafka:9094
      server.advertised.listeners: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      server.listener.security.protocol.map: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      server.inter.broker.listener.name: INSIDE
      server.auto_create_topics_enable: "false"
    depends_on:
      - zookeeper
    restart: on-failure
